/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | www.openfoam.com
     \\/     M anipulation  |
-------------------------------------------------------------------------------
    Copyright (C) 2011-2016 OpenFOAM Foundation
    Copyright (C) 2017 OpenCFD Ltd
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

#include "WallThermalResistanceFvPatchScalarField.H"
#include "addToRunTimeSelectionTable.H"
#include "volFields.H"
#include "surfaceFields.H"
#include "IOReferencer.H"
#include "interpolationTable.H"


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //



// * * * * * * * * * * * * * * * * Constructors  * * * * * * * * * * * * * * //

Foam::WallThermalResistanceFvPatchScalarField::WallThermalResistanceFvPatchScalarField
(
    const fvPatch& p,
    const DimensionedField<scalar, volMesh>& iF
)
:
    fixedValueFvPatchScalarField(p, iF),
	R_wall(0),
	T_inf(1)	
{
	//If this constructor is called, we were auto-generated by a T-field, load in the T-field parameters:
	
}


Foam::WallThermalResistanceFvPatchScalarField::WallThermalResistanceFvPatchScalarField
(
    const WallThermalResistanceFvPatchScalarField& ptf,
    const fvPatch& p,
    const DimensionedField<scalar, volMesh>& iF,
    const fvPatchFieldMapper& mapper
)
:
    fixedValueFvPatchScalarField(ptf, p, iF, mapper),
	R_wall(ptf.R_wall),
	T_inf(ptf.T_inf)
{}


Foam::WallThermalResistanceFvPatchScalarField::WallThermalResistanceFvPatchScalarField
(
    const fvPatch& p,
    const DimensionedField<scalar, volMesh>& iF,
    const dictionary& dict
)
:
    fixedValueFvPatchScalarField(p, iF, dict),
	R_wall(dict.get<scalar>("R_wall")),
	T_inf(dict.get<scalar>("T_inf"))
{}


Foam::WallThermalResistanceFvPatchScalarField::WallThermalResistanceFvPatchScalarField
(
    const WallThermalResistanceFvPatchScalarField& pfopsf
)
:
    fixedValueFvPatchScalarField(pfopsf),
	R_wall(pfopsf.R_wall),
	T_inf(pfopsf.T_inf)
{}


Foam::WallThermalResistanceFvPatchScalarField::WallThermalResistanceFvPatchScalarField
(
    const WallThermalResistanceFvPatchScalarField& pfopsf,
    const DimensionedField<scalar, volMesh>& iF
)
:
    fixedValueFvPatchScalarField(pfopsf, iF),
	R_wall(pfopsf.R_wall),
	T_inf(pfopsf.T_inf)
{}


// * * * * * * * * * * * * * * * Member Functions  * * * * * * * * * * * * * //

void Foam::WallThermalResistanceFvPatchScalarField::copyParams( const WallThermalResistanceFvPatchScalarField& p )
{
	R_wall = p.R_wall;
	T_inf = p.T_inf;
}

void Foam::WallThermalResistanceFvPatchScalarField::updateCoeffs()
{
    if (updated())
    {
        return;
    }
	//Get references to T for cell center and for wall
	const scalarField T_c = patch().lookupPatchField<volScalarField, scalar>("T").patchInternalField();
	const scalarField T_w = patch().lookupPatchField<volScalarField, scalar>("T");
	
	
	
	//Scale conductivity of internal material by vol fraction of liquid phase on wall:
	//Get name of the condensed phase (phase 1)
	const dictionary& transportProperties = db().lookupObject<dictionary>("transportProperties");
	const word& CondensedPhaseName = transportProperties.get<wordList>("phases")[0];
	const scalarField& a_w = patch().lookupPatchField<volScalarField, scalar>("alpha." + CondensedPhaseName);

	
	//Get lookup table for T->k and calculate k on wall
	const interpolationTable<scalar>& k_T_ = db().lookupObject<IOReferencer<interpolationTable<scalar> > >( "k_T" )();
	const scalarField k_f = k_T_.interpolateValues( T_w ) * a_w;

	//Resistance network solution for T_w
	const scalarField T_w_up =     T_c*( 1.0 /( 1.0/(patch().deltaCoeffs()*k_f*R_wall) + 1.0) )
	                           + T_inf*( 1.0 /( k_f*R_wall*patch().deltaCoeffs() + 1.0) );
	 
	//Write out T or h to field, depending on what field is calling this code
	const word& fieldName( internalField().name() );
	if (fieldName == "h")
	{
		const interpolationTable<scalar>& h_T_ = db().lookupObject<IOReferencer<interpolationTable<scalar> > >( "h_T" )();
		operator==( h_T_.interpolateValues(T_w_up) );
	}
	else if (fieldName == "T")
	{
		operator==(T_w_up);
	}


    fixedValueFvPatchScalarField::updateCoeffs();
}


void Foam::WallThermalResistanceFvPatchScalarField::write(Ostream& os) const
{
    fvPatchScalarField::write(os);
	os.writeEntry("R_wall", R_wall);
	os.writeEntry("T_inf", T_inf);
    writeEntry("value", os);
}


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{
    makePatchTypeField
    (
        fvPatchScalarField,
        WallThermalResistanceFvPatchScalarField
    );
};


// ************************************************************************* //
